version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nest-app
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/barcode_scanner'

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barcode_scanner
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
